### ISSUE TITLE
Fail to build any palette

### ISSUE THREAD

**Issue by yblein** [liflab/beepbeep-3-palettes#2]
Trying to compile any palette results in an error similar to the following one:

```
[javac] beepbeep-3-palettes-master/Fol/src/ca/uqac/lif/cep/fol/QuantifierFunction.java:10: error: cannot find symbol
[javac] import ca.uqac.lif.cep.functions.FunctionException;
```

Indeed, the BeepBeep jar file does not contain the class FunctionException:
```
$ jar -tf beepbeep-3.jar | grep FunctionException | wc -l
0
```

I am using the latest BeepBeep release (3-0.5-alpha) and JDK 8.

**Comment by sylvainhalle** [comment]
Palettes require the latest version of BeepBeep built from the sources. I'll make a release from this code and update the build scripts.

**Comment by sylvainhalle** [comment]
Compilation of palettes should work with the newly released 0.6-alpha. Thanks for pointing this out!
